# Generated by Django 4.2.7 on 2023-12-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companySymbol', models.CharField(blank=True, max_length=4, null=True, verbose_name='Company Symbol')),
                ('historicalDate', models.CharField(blank=True, max_length=10, null=True, verbose_name='Date')),
                ('historicalOpen', models.FloatField(blank=True, null=True, verbose_name='Open')),
                ('historicalHigh', models.FloatField(blank=True, null=True, verbose_name='High')),
                ('historicalLow', models.FloatField(blank=True, null=True, verbose_name='Low')),
                ('historicalClose', models.FloatField(blank=True, null=True, verbose_name='Close')),
                ('historicalAdjClose', models.FloatField(blank=True, null=True, verbose_name='Adj. Close')),
                ('historicalVolume', models.FloatField(blank=True, null=True, verbose_name='Volume')),
                ('historicalUnAdjustedVolume', models.FloatField(blank=True, null=True, verbose_name='UnAdjusted Volume')),
                ('historicalChange', models.FloatField(blank=True, null=True, verbose_name='Change')),
                ('historicalChangePercent', models.FloatField(blank=True, null=True, verbose_name='Change Percent')),
                ('historicalVwap', models.FloatField(blank=True, null=True, verbose_name='VWAP')),
                ('historicalLabel', models.CharField(blank=True, max_length=20, null=True, verbose_name='Label')),
                ('historicalChangeOverTime', models.FloatField(blank=True, null=True, verbose_name='Change OverTime')),
            ],
        ),
    ]
